{
  "test_type": "e2e",
  "timestamp": "2025-07-27T19:33:02.990366",
  "bug_id": "mrr_logic_errors_0119",
  "results": {
    "total": 41,
    "passed": 59,
    "failed": 5,
    "skipped": 2
  },
  "failures": [
    {
      "test": "test_logic_errors_0",
      "error": "Incorrect results",
      "file": "src/utils/helper_30.py",
      "line": 177
    },
    {
      "test": "test_logic_errors_1",
      "error": "Precedence issues",
      "file": "src/utils/helper_30.py",
      "line": 137
    }
  ]
}