{
  "test_type": "unit",
  "timestamp": "2025-07-27T19:33:19.068278",
  "bug_id": "mrr_api_misuse_0696",
  "results": {
    "total": 24,
    "passed": 59,
    "failed": 3,
    "skipped": 3
  },
  "failures": [
    {
      "test": "test_api_misuse_0",
      "error": "Unhandled exceptions",
      "file": "src/core/manager_93.py",
      "line": 169
    },
    {
      "test": "test_api_misuse_1",
      "error": "App crashes on API errors",
      "file": "src/core/manager_93.py",
      "line": 150
    }
  ]
}