{
  "test_type": "e2e",
  "timestamp": "2025-07-27T19:32:31.510288",
  "bug_id": "mrr_logic_errors_0502",
  "results": {
    "total": 73,
    "passed": 63,
    "failed": 6,
    "skipped": 1
  },
  "failures": [
    {
      "test": "test_logic_errors_0",
      "error": "Incorrect computation results",
      "file": "src/data/model_22.py",
      "line": 51
    },
    {
      "test": "test_logic_errors_1",
      "error": "Unit tests fail",
      "file": "src/data/model_22.py",
      "line": 108
    }
  ]
}